# Generated by Django 5.1.6 on 2025-03-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_order_created_at_remove_order_total_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='cart',
        ),
    ]
